### ISSUE TITLE
build on centos7 with gcc 9.3.0 support AVX512 failed  ‘_mm_mul256_pd’ was not declared

### ISSUE THREAD

**Issue by xvjinkun** [t0rakka/mango#58]
-- Found Threads: TRUE  
-- F16C: half conversion enabled (2012)
-- BMI+LZCNT: enabled (2013)
-- BMI2: enabled (2013)
-- SIMD: AVX-512 (2015)
-- Configuring done
-- Generating done
-- Build files have been written to: /home/xjk1/mango/mango-0.8.14/build/cmake
[xjk1@hwbj4-mtlab-cpu-tmp-20200511-10-17-46-27.meitu-inc.com cmake]$ make
Scanning dependencies of target mango
[  0%] Building CXX object CMakeFiles/mango.dir/home/xjk1/mango/mango-0.8.14/source/mango/core/aes.cpp.o
[  0%] Building CXX object CMakeFiles/mango.dir/home/xjk1/mango/mango-0.8.14/source/mango/core/buffer.cpp.o
[  0%] Building CXX object CMakeFiles/mango.dir/home/xjk1/mango/mango-0.8.14/source/mango/core/compress.cpp.o
In file included from /home/xjk1/mango/mango-0.8.14/build/../include/mango/math/../simd/simd.hpp:247,
                 from /home/xjk1/mango/mango-0.8.14/build/../include/mango/math/vector.hpp:9,
                 from /home/xjk1/mango/mango-0.8.14/build/../include/mango/math/math.hpp:7,
                 from /home/xjk1/mango/mango-0.8.14/source/mango/core/compress.cpp:14:
/home/xjk1/mango/mango-0.8.14/build/../include/mango/math/../simd/avx512_double256.hpp: In function ‘mango::simd::f64x4 mango::simd::msub(mango::simd::f64x4, mango::simd::f64x4, mango::simd::f64x4)’:
/home/xjk1/mango/mango-0.8.14/build/../include/mango/math/../simd/avx512_double256.hpp:300:30: error: ‘_mm_mul256_pd’ was not declared in this scope; did you mean ‘_mm_mul_pd’?
  300 |         return _mm256_sub_pd(_mm_mul256_pd(b, c), a);
      |                              ^~~~~~~~~~~~~
      |                              _mm_mul_pd
In file included from /home/xjk1/mango/mango-0.8.14/build/../include/mango/math/../simd/simd.hpp:248,
                 from /home/xjk1/mango/mango-0.8.14/build/../include/mango/math/vector.hpp:9,
                 from /home/xjk1/mango/mango-0.8.14/build/../include/mango/math/math.hpp:7,
                 from /home/xjk1/mango/mango-0.8.14/source/mango/core/compress.cpp:14:
/home/xjk1/mango/mango-0.8.14/build/../include/mango/math/../simd/avx512_double512.hpp: In function ‘mango::simd::f64x8 mango::simd::msub(mango::simd::f64x8, mango::simd::f64x8, mango::simd::f64x8)’:
/home/xjk1/mango/mango-0.8.14/build/../include/mango/math/../simd/avx512_double512.hpp:169:30: error: ‘_mm_mul512_pd’ was not declared in this scope; did you mean ‘_mm_mul_pd’?
  169 |         return _mm512_sub_pd(_mm_mul512_pd(b, c), a);
      |                              ^~~~~~~~~~~~~
      |                              _mm_mul_pd
make[2]: *** [CMakeFiles/mango.dir/home/xjk1/mango/mango-0.8.14/source/mango/core/compress.cpp.o] Error 1
make[1]: *** [CMakeFiles/mango.dir/all] Error 2
make: *** [all] Error 2

**Comment by t0rakka** [comment]
Thanks the the head's up, fixed the typos. It seems AVX512 target is being compiled w/o __FMA__ defined, which is odd.. but legal. The CPU should have FMA3 when it has AVX512, when you compiling for that SIMD ISA try to figure out why the FMA wasn't enabled.. it should give a small speed boost in some math operations (if it makes any difference to your use case).

At least the typos are fixed and it should compile better (I tested by forcing FMA3 off).

**Comment by t0rakka** [comment]
Also careful with the extended instructions; you might want to have a runtime check early in your program for the features so that you can report correct error message to the user when their CPU doesn't support these things. The compiler is now free to use these instructions anywhere it likes, even when not invoked by the intrinsics..

u64 flags = mango::getCPUFlags();
if (!(flags & mango::INTEL_F16C)) { ... error ... }

I'm myself compiling different .so/.dll 's and dynamically loading them based off the CPU caps but that's higher-level stuff that is not dealt in the low-level library here. Dynamic dispatching is supported as compiler extension for gcc but most of my code is portable and cross-compiler so can't leverage that stuff at all. :(

**Comment by xvjinkun** [comment]
Here is my cpu info ,it has avx512 but no fma3 found! so u64 flags = mango::getCPUFlags() will not has fma3 FLAGS

processor	: 31
vendor_id	: GenuineIntel
cpu family	: 6
model		: 85
model name	: Intel(R) Xeon(R) Gold 6266C CPU @ 3.00GHz
stepping	: 7
microcode	: 0x1
cpu MHz		: 3000.000
cache size	: 30976 KB
physical id	: 1
siblings	: 16
core id		: 7
cpu cores	: 8
apicid		: 31
initial apicid	: 31
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc eagerfpu pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 arat avx512_vnni md_clear spec_ctrl intel_stibp flush_l1d arch_capabilities

**Comment by t0rakka** [comment]
Above flags has "fma" listed, which is FMA3. This is a bit of a history lesson, but when the FMA came out, Intel had their own variant and AMD had their own. The AMD one is called FMA4 and Intel one is called FMA3. The FMA3 is these days supported by both AMD and Intel, while the FMA4 stayed AMD-only and is more rare for that reason. ;)

You can manually enable fma (FMA3, to be exact) with "-mfma" with GCC and CLANG, at least. But as usual, any time you enable more CPU features for the compiler they can be will be used so careful out there! :)

I add specific ENABLE_FMA switch to the cmake scripts; I didn't need those previously as for some reason I always had it enabled automatically when I did -DENABLE_AVX512=ON.. not sure if you want or need those, but I sure do, so adding the support.. of course, this never stopped end user from doing what they want as this only affects how the library itself is built, not how it is used.. you could still enable any settings in your projects and the configure.hpp header should pick most relevant stuff up..

**Comment by xvjinkun** [comment]
Thank you very much ,i build success after set define ENABLE_FMA=ON,then I found it perform very poor performance increasement than AVX2,just same
